{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" .Release.Name) .Values.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.component | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") }}
type: Opaque
stringData:
  {{- if .Values.secret.databaseUrl }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secret.coordApiKeys }}
  COORD_API_KEYS: {{ .Values.secret.coordApiKeys | quote }}
  {{- end }}
  {{- range $name, $value := .Values.secret.extra }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
