import type {
  CoordAgentSummary,
  CoordMessageSummary,
  CoordPlanSummary,
  CoordTaskSummary,
} from "@/lib/coord/types";

export const stubAgents: CoordAgentSummary[] = [
  {
    id: "orch",
    name: "orch",
    status: "running",
    enabled: true,
    driver: "claude",
    currentTaskId: "mcp-012",
    lastHeartbeatAt: "2026-04-22T09:32:00.000Z",
    capabilities: {
      domains: ["coord", "frontend"],
      taskTypes: ["planning", "delivery"],
    },
    metadata: { version: "preview", notes: "Shell coordination in progress" },
  },
  {
    id: "fe",
    name: "fe",
    status: "idle",
    enabled: true,
    driver: "codex",
    currentTaskId: "mcp-013",
    lastHeartbeatAt: "2026-04-22T09:29:00.000Z",
    capabilities: {
      domains: ["web", "dashboard"],
      taskTypes: ["feature", "ux"],
    },
    metadata: { version: "preview", focus: "agents-panel" },
  },
  {
    id: "be",
    name: "be",
    status: "idle",
    enabled: true,
    driver: "gemini",
    currentTaskId: "mcp-021",
    lastHeartbeatAt: "2026-04-22T09:10:00.000Z",
    capabilities: {
      domains: ["api", "schema"],
      taskTypes: ["feature", "migration"],
    },
    metadata: { version: "preview", region: "psws.pl" },
  },
  {
    id: "runner",
    name: "runner",
    status: "offline",
    enabled: false,
    driver: "inherit",
    currentTaskId: null,
    lastHeartbeatAt: "2026-04-22T08:42:00.000Z",
    capabilities: {
      domains: ["runner", "coord"],
      taskTypes: ["ops", "execution"],
    },
    metadata: { version: "preview", notes: "Awaiting redeploy" },
  },
  {
    id: "devops",
    name: "devops",
    status: "blocked",
    enabled: true,
    driver: "codex",
    currentTaskId: "mcp-024",
    lastHeartbeatAt: "2026-04-22T09:18:00.000Z",
    capabilities: {
      domains: ["deploy", "release"],
      taskTypes: ["infra", "ops"],
    },
    metadata: { version: "preview", focus: "deploy" },
  },
];

export const stubTasks: CoordTaskSummary[] = [
  {
    id: "mcp-012",
    title: "Dashboard foundation",
    description: "Create the reusable app shell, fetch client, and SSE status.",
    status: "done",
    priority: "high",
    owner: "fe",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T08:55:00.000Z",
    updatedAt: "2026-04-22T09:32:00.000Z",
  },
  {
    id: "mcp-013",
    title: "Agents panel",
    description: "Layer agent cards and controls onto the shared dashboard shell.",
    status: "done",
    priority: "high",
    owner: "fe",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T08:58:00.000Z",
    updatedAt: "2026-04-22T09:40:00.000Z",
  },
  {
    id: "mcp-014",
    title: "Tasks kanban",
    description: "Add lane grouping and task workflow interactions.",
    status: "in_progress",
    priority: "high",
    owner: "fe",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T08:59:00.000Z",
    updatedAt: "2026-04-22T09:48:00.000Z",
  },
  {
    id: "mcp-015",
    title: "Messages timeline",
    description: "Render the coordination message stream with acknowledgment states.",
    status: "review",
    priority: "normal",
    owner: "fe",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T09:03:00.000Z",
    updatedAt: "2026-04-22T09:35:00.000Z",
  },
  {
    id: "mcp-016",
    title: "Plans panel",
    description: "Show plan progress cards with task counts and status transitions.",
    status: "pending",
    priority: "normal",
    owner: "fe",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T09:05:00.000Z",
    updatedAt: "2026-04-22T09:05:00.000Z",
  },
  {
    id: "mcp-021",
    title: "Agent transport endpoints",
    description: "Publish agent detail and configuration endpoints from coord-api.",
    status: "blocked",
    priority: "high",
    owner: "be",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T09:01:00.000Z",
    updatedAt: "2026-04-22T09:10:00.000Z",
  },
  {
    id: "mcp-022",
    title: "Runner restart",
    description: "Recover the generic runner after the last tool dispatch regression.",
    status: "pending",
    priority: "normal",
    owner: "runner",
    planId: "plan-mcp-coord-build",
    createdAt: "2026-04-22T08:40:00.000Z",
    updatedAt: "2026-04-22T08:42:00.000Z",
  },
  {
    id: "mcp-024",
    title: "Helm release automation",
    description: "Publish the chart and dashboard images through the release workflow.",
    status: "blocked",
    priority: "urgent",
    owner: "devops",
    planId: "plan-axiom-coord-deploy",
    createdAt: "2026-04-22T09:12:00.000Z",
    updatedAt: "2026-04-22T09:18:00.000Z",
  },
];

export const stubMessages: CoordMessageSummary[] = [
  {
    id: "msg-001",
    from: "orch",
    to: "fe",
    type: "assignment",
    body: "Take ownership of mcp-012 and prepare the dashboard foundation.",
    status: "acknowledged",
    createdAt: "2026-04-22T09:00:00.000Z",
  },
  {
    id: "msg-002",
    from: "fe",
    to: "orch",
    type: "status",
    body: "Scaffold is ready for typed API wiring and route shells.",
    status: "pending",
    createdAt: "2026-04-22T09:20:00.000Z",
  },
  {
    id: "msg-003",
    from: "orch",
    to: "be",
    type: "handoff",
    body: "Please publish get_agent, configure_agent, and assign_task transport when the API panel is ready.",
    status: "pending",
    createdAt: "2026-04-22T09:09:00.000Z",
  },
  {
    id: "msg-004",
    from: "runner",
    to: "orch",
    type: "incident",
    body: "Worker pool terminated during the last dry run. Awaiting restart instructions.",
    status: "acknowledged",
    createdAt: "2026-04-22T08:43:00.000Z",
  },
  {
    id: "msg-005",
    from: "orch",
    to: "fe",
    type: "assignment",
    body: "Ship the agents grid with detail sheet and optimistic panel interactions.",
    status: "acknowledged",
    createdAt: "2026-04-22T09:28:00.000Z",
  },
];

export const stubPlans: CoordPlanSummary[] = [
  {
    id: "plan-mcp-coord-build",
    name: "Build coord platform",
    description:
      "Ship the standalone API, dashboard, charts, and deployment path.",
    status: "active",
    owner: "orch",
    createdAt: "2026-04-22T08:30:00.000Z",
    updatedAt: "2026-04-22T09:32:00.000Z",
    taskCounts: {
      total: 7,
      done: 2,
      active: 4,
      blocked: 1,
    },
  },
  {
    id: "plan-axiom-coord-deploy",
    name: "Deploy coord platform",
    description:
      "Package and deploy coord-api plus coord-web into the psws.pl cluster.",
    status: "paused",
    owner: "devops",
    createdAt: "2026-04-22T09:10:00.000Z",
    updatedAt: "2026-04-22T09:18:00.000Z",
    taskCounts: {
      total: 1,
      done: 0,
      active: 0,
      blocked: 1,
    },
  },
];
